/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonTitle: typeof import('./../components/common-title.vue')['default']
    CustomNavBar: typeof import('./../components/custom-nav-bar.vue')['default']
    CustomRefresher: typeof import('./../components/custom-refresher/custom-refresher.vue')['default']
    FgNavbar: typeof import('./../components/fg-navbar/fg-navbar.vue')['default']
    ThemeItem: typeof import('./../components/theme-item.vue')['default']
  }
}
